name = "jewelry-store"
compatibility_date = "2026-05-15"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ADMIN_EMAIL = "admin@example.com"
FROM_EMAIL = "onboarding@resend.dev"
R2_BUCKET_NAME = "jewelry-store-assets"

[[d1_databases]]
binding = "DB"
database_name = "jewelry-store-db"
database_id = "f322a821-758e-4524-aceb-57646d29eb2a"
remote = true

[[r2_buckets]]
binding = "R2"
bucket_name = "jewelry-store-assets"
remote = true
